const appVersion = '1.1.42';
const appBuildNumber = 44;
const appVersionLabel = '1.1.42+44';
const appVersionHistory = <Map<String, String>>[
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: remove duplicate one-piece clothing color'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: show clothing details per selected garment'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: save clothing designs as combinations'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: prioritize combination editor upper panel'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: enlarge combination editor upper section'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: expand combination editor workspace'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add reusable prompt combinations'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: scope clothing styles and wear states'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：Merge remote-tracking branch \'origin/main\''},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：Merge remote-tracking branch \'origin/main\''},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: organize eye colors and special eye tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add hierarchical color selectors'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: group person prompts and expand paizuri tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add object-linked actions and remove avatar preview'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add trim colors accessory placement and masturbation tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add scoped randomization and avatar preview'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: expand prompt tags and split hair colors'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: preserve characters during reverse prompt import'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: repair category chip widget syntax'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: reverse composed prompt tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add prompt tag reverse import'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: compose clothing color and detail tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: group multi-character prompt tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: make generated Chinese tags removable'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: wrap category filters for small screens'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: map imported characters to anime tags and close lookup'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: show imported anime characters in prompt content'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: improve button contrast and adaptive category widths'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: support Chinese separators for extra tags'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: translate extra positive tags and expand expression catalog'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：fix: make tag controls responsive'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: expand pose detail skirt lengths and anime aliases'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: expand hairstyles actions and objects'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add automatic hair length negative guards'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: derive people count from character cards'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add editable negative tag library'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add scene catalog and random outfits'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add gothic styles and innerwear layering'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: split clothing colors and enforce outfit layers'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: add reset control and section navigation'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: refine character overrides and clothing filters'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '自動偵測：feat: scope tags to each character'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '加入版本顯示、更新提示、版本歷程與自動追加版本號工具。'},
  {'version': '', 'build': '', 'label': '', 'date': '', 'notes': '建立 BetterWaifu Amanatsu 1.1 提示標籤組合工具。'},
];
