import 'catalog_data.dart';

String _clothingSlug(String value) => value
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
    .replaceAll(RegExp(r'^_+|_+$'), '');

CatalogTagData _clothingTag({
  required String id,
  required String group,
  required String zh,
  required String en,
  String? conflictGroup,
}) =>
    CatalogTagData(
      id: id,
      group: group,
      zh: zh,
      en: en,
      order: 2,
      conflictGroup: conflictGroup,
    );

List<CatalogTagData> _garments(
  String group,
  String scope,
  List<(String, String)> values,
) =>
    values
        .map(
          (value) => _clothingTag(
            id: 'taxonomy_${scope}_${_clothingSlug(value.$2)}',
            group: group,
            zh: value.$1,
            en: value.$2,
            conflictGroup: '${scope}_garment',
          ),
        )
        .toList();

List<CatalogTagData> _dimensions(
  String scope,
  String dimension,
  List<(String, String)> values,
) =>
    values
        .map(
          (value) => _clothingTag(
            id: 'taxonomy_${scope}_${dimension}_${_clothingSlug(value.$2)}',
            group: 'clothing_scope_${scope}_$dimension',
            zh: value.$1,
            en: value.$2,
            conflictGroup: '${scope}_$dimension',
          ),
        )
        .toList();

List<CatalogTagData> _overall(
  String idPrefix,
  String group,
  List<(String, String)> values,
) =>
    values
        .map(
          (value) => _clothingTag(
            id: '${idPrefix}_${_clothingSlug(value.$2)}',
            group: group,
            zh: value.$1,
            en: value.$2,
            conflictGroup: idPrefix,
          ),
        )
        .toList();

const _garmentScopes = <String>[
  'top',
  'pants',
  'shorts',
  'skirt',
  'onepiece',
  'outerwear',
  'costume',
  'underwear',
  'bra',
  'panties',
  'socks',
  'shoes',
  'accessory',
];

const _materials = <(String, String)>[
  ('棉質', 'cotton'),
  ('亞麻', 'linen'),
  ('羊毛', 'wool'),
  ('針織', 'knit'),
  ('羅紋針織', 'ribbed knit'),
  ('喀什米爾', 'cashmere'),
  ('丹寧', 'denim'),
  ('皮革', 'leather'),
  ('麂皮', 'suede'),
  ('絲質', 'silk'),
  ('緞面', 'satin'),
  ('雪紡', 'chiffon'),
  ('歐根紗', 'organza'),
  ('薄紗', 'tulle'),
  ('蕾絲', 'lace'),
  ('鉤針編織', 'crochet'),
  ('網眼布', 'mesh'),
  ('透視布料', 'sheer fabric'),
  ('天鵝絨', 'velvet'),
  ('燈芯絨', 'corduroy'),
  ('乳膠', 'latex'),
];

const _details = <(String, String)>[
  ('荷葉邊', 'ruffles'),
  ('褶邊', 'frills'),
  ('百褶', 'pleats'),
  ('抽褶', 'gathered fabric'),
  ('蝴蝶結', 'bow'),
  ('緞帶', 'ribbon'),
  ('蕾絲飾邊', 'lace trim'),
  ('毛皮飾邊', 'fur trim'),
  ('羽毛飾邊', 'feather trim'),
  ('刺繡', 'embroidery'),
  ('花卉刺繡', 'floral embroidery'),
  ('珠飾', 'beading'),
  ('亮片', 'sequins'),
  ('水鑽', 'rhinestones'),
  ('珍珠', 'pearls'),
  ('鈕扣', 'buttons'),
  ('拉鍊', 'zipper'),
  ('扣環', 'buckles'),
  ('腰帶', 'belt'),
  ('鏈條', 'chains'),
  ('綁帶', 'straps'),
  ('鏤空', 'cutout'),
  ('側邊鏤空', 'side cutout'),
  ('腰部鏤空', 'waist cutout'),
  ('背部鏤空', 'back cutout'),
  ('開衩', 'slit'),
  ('側開衩', 'side slit'),
  ('前開衩', 'front slit'),
  ('高開衩', 'high slit'),
  ('繫帶', 'lace-up'),
  ('馬甲繫帶', 'corset lacing'),
  ('多層次', 'layered'),
  ('垂墜', 'draped'),
  ('抓皺', 'ruched'),
  ('滾邊', 'piping'),
];

const _patterns = <(String, String)>[
  ('純色', 'solid color'),
  ('雙色', 'two-tone'),
  ('漸層', 'gradient'),
  ('撞色拼接', 'color block'),
  ('條紋', 'striped'),
  ('直條紋', 'vertical stripes'),
  ('橫條紋', 'horizontal stripes'),
  ('格紋', 'plaid'),
  ('蘇格蘭格紋', 'tartan'),
  ('棋盤格', 'checkered'),
  ('圓點', 'polka dot'),
  ('花卉圖案', 'floral pattern'),
  ('玫瑰圖案', 'rose pattern'),
  ('櫻花圖案', 'cherry blossom pattern'),
  ('葉片圖案', 'leaf pattern'),
  ('幾何圖案', 'geometric pattern'),
  ('菱格紋', 'diamond pattern'),
  ('豹紋', 'leopard print'),
  ('斑馬紋', 'zebra print'),
  ('迷彩', 'camouflage'),
  ('星星圖案', 'star pattern'),
  ('愛心圖案', 'heart pattern'),
  ('角色印花', 'character print'),
  ('圖像印花', 'graphic print'),
];

/// Clothing data follows a composable taxonomy. Garment nouns stay separate
/// from cut, fit, length, material, detail, pattern, color, and overall style.
final List<CatalogTagData> clothingTaxonomyTags = <CatalogTagData>[
  ..._garments('上衣', 'top', const [
    ('T恤', 't-shirt'),
    ('襯衫', 'shirt'),
    ('正裝襯衫', 'dress shirt'),
    ('鈕扣襯衫', 'button-up shirt'),
    ('牛津襯衫', 'Oxford shirt'),
    ('女式襯衫', 'blouse'),
    ('背心', 'tank top'),
    ('細肩帶上衣', 'camisole'),
    ('短版上衣', 'crop top'),
    ('平口上衣', 'tube top'),
    ('繞頸上衣', 'halter top'),
    ('針織上衣', 'knit top'),
    ('毛衣', 'sweater'),
    ('開襟衫', 'cardigan'),
    ('連帽上衣', 'hoodie'),
    ('運動衫', 'sweatshirt'),
    ('馬甲上衣', 'corset top'),
    ('西裝背心', 'suit vest'),
    ('籃球球衣', 'basketball jersey'),
  ]),
  ..._garments('褲子', 'pants', const [
    ('直筒褲', 'straight-leg pants'),
    ('窄管褲', 'slim pants'),
    ('緊身褲', 'skinny pants'),
    ('寬褲', 'wide-leg pants'),
    ('喇叭褲', 'flared pants'),
    ('錐形褲', 'tapered pants'),
    ('九分褲', 'cropped pants'),
    ('牛仔褲', 'jeans'),
    ('西裝褲', 'dress pants'),
    ('工裝褲', 'cargo pants'),
    ('慢跑褲', 'joggers'),
    ('運動長褲', 'sweatpants'),
    ('內搭褲', 'leggings'),
    ('皮褲', 'leather pants'),
  ]),
  ..._garments('短褲', 'shorts', const [
    ('短褲', 'shorts'),
    ('熱褲', 'short shorts'),
    ('高腰短褲', 'high-waisted shorts'),
    ('丹寧短褲', 'denim shorts'),
    ('百慕達短褲', 'Bermuda shorts'),
    ('運動短褲', 'sports shorts'),
    ('自行車短褲', 'bike shorts'),
    ('工裝短褲', 'cargo shorts'),
    ('燈籠短褲', 'bloomers'),
  ]),
  ..._garments('裙子', 'skirt', const [
    ('A字裙', 'a-line skirt'),
    ('鉛筆裙', 'pencil skirt'),
    ('百褶裙', 'pleated skirt'),
    ('圓裙', 'circle skirt'),
    ('傘裙', 'flared skirt'),
    ('包裙', 'wrap skirt'),
    ('分層裙', 'tiered skirt'),
    ('魚尾裙', 'mermaid skirt'),
    ('蓬蓬裙', 'tutu skirt'),
    ('牛仔裙', 'denim skirt'),
    ('運動裙', 'sports skirt'),
  ]),
  ..._garments('服裝', 'onepiece', const [
    ('洋裝', 'dress'),
    ('連身裙', 'one-piece dress'),
    ('晚禮服', 'evening gown'),
    ('雞尾酒洋裝', 'cocktail dress'),
    ('背心裙', 'sundress'),
    ('襯衫裙', 'shirt dress'),
    ('針織洋裝', 'knit dress'),
    ('包裹式洋裝', 'wrap dress'),
    ('吊帶洋裝', 'slip dress'),
    ('舞會禮服', 'ball gown'),
    ('連身褲', 'jumpsuit'),
    ('連身短褲', 'romper'),
  ]),
  ..._garments('外套', 'outerwear', const [
    ('西裝外套', 'blazer'),
    ('夾克', 'jacket'),
    ('牛仔外套', 'denim jacket'),
    ('皮夾克', 'leather jacket'),
    ('飛行夾克', 'bomber jacket'),
    ('運動外套', 'track jacket'),
    ('風衣', 'trench coat'),
    ('大衣', 'coat'),
    ('斗篷', 'cape'),
    ('披肩', 'shawl'),
    ('雨衣', 'raincoat'),
    ('實驗袍', 'lab coat'),
  ]),
  ..._garments('特殊服裝', 'costume', const [
    ('校服', 'school uniform'),
    ('水手服', 'sailor uniform'),
    ('運動制服', 'sports uniform'),
    ('女僕裝', 'maid outfit'),
    ('護士服', 'nurse uniform'),
    ('警察制服', 'police uniform'),
    ('軍服', 'military uniform'),
    ('啦啦隊服', 'cheerleading uniform'),
    ('和服', 'kimono'),
    ('浴衣', 'yukata'),
    ('弓道服', 'kyudo uniform'),
    ('巫女服', 'miko outfit'),
    ('忍者套裝', 'ninja outfit'),
    ('武術服', 'martial arts uniform'),
    ('體操服', 'gymnastics leotard'),
    ('泳裝', 'swimsuit'),
    ('婚紗', 'wedding dress'),
    ('黑魔導女孩服裝', 'Dark Magician Girl outfit'),
  ]),
];

final List<CatalogTagData> clothingDimensionTags = <CatalogTagData>[
  for (final scope in _garmentScopes)
    ..._dimensions(scope, 'material', _materials),
  for (final scope in _garmentScopes) ..._dimensions(scope, 'detail', _details),
  for (final scope in _garmentScopes)
    ..._dimensions(scope, 'pattern', _patterns),
  for (final scope in const [
    'top',
    'pants',
    'shorts',
    'skirt',
    'onepiece',
    'outerwear'
  ])
    ..._dimensions(scope, 'fit', const [
      ('貼身', 'fitted'),
      ('修身', 'slim fit'),
      ('合身', 'regular fit'),
      ('寬鬆', 'loose fit'),
      ('超寬鬆', 'oversized'),
      ('垂墜版型', 'relaxed fit'),
      ('箱型版型', 'boxy fit'),
    ]),
  ..._dimensions('top', 'cut', const [
    ('圓領', 'crew neck'),
    ('V領', 'v-neck'),
    ('高領', 'turtleneck'),
    ('立領', 'stand collar'),
    ('一字領', 'boat neck'),
    ('露肩', 'off-shoulder'),
    ('單肩', 'one-shoulder'),
    ('繞頸', 'halter neck'),
    ('無袖', 'sleeveless'),
    ('短袖', 'short sleeves'),
    ('長袖', 'long sleeves'),
    ('泡泡袖', 'puff sleeves'),
    ('喇叭袖', 'bell sleeves'),
    ('削肩', 'racerback'),
  ]),
  for (final scope in const ['pants', 'shorts', 'skirt', 'onepiece'])
    ..._dimensions(scope, 'cut', const [
      ('自然腰', 'natural waist'),
      ('高腰', 'high-waisted'),
      ('低腰', 'low-waisted'),
      ('帝王腰線', 'empire waist'),
      ('低腰線', 'drop waist'),
    ]),
  ..._dimensions('onepiece', 'cut', const [
    ('無肩帶', 'strapless'),
    ('單肩', 'one-shoulder'),
    ('露肩', 'off-shoulder'),
    ('繞頸', 'halter neck'),
    ('露背', 'backless'),
    ('深V領', 'plunging neckline'),
  ]),
  ..._dimensions('bra', 'cut', const [
    ('有鋼圈', 'underwire'),
    ('無鋼圈', 'wireless'),
    ('集中托高', 'push-up'),
    ('無肩帶', 'strapless'),
    ('三角罩杯', 'triangle cups'),
    ('前扣', 'front clasp'),
  ]),
  ..._dimensions('panties', 'cut', const [
    ('高腰', 'high-waisted'),
    ('低腰', 'low-rise'),
    ('高衩', 'high-cut'),
    ('低衩', 'low-cut'),
    ('側綁帶', 'side-tie'),
    ('無痕', 'seamless'),
  ]),
  ..._dimensions('top', 'length', const [
    ('超短版', 'ultra cropped'),
    ('短版', 'cropped'),
    ('及腰', 'waist length'),
    ('及臀', 'hip length'),
    ('加長版', 'longline'),
  ]),
  ..._dimensions('pants', 'length', const [
    ('七分長', 'cropped length'),
    ('九分長', 'ankle length'),
    ('全長', 'full length'),
  ]),
  ..._dimensions('shorts', 'length', const [
    ('極短', 'micro length'),
    ('短版', 'short length'),
    ('百慕達長度', 'Bermuda length'),
  ]),
  for (final scope in const ['skirt', 'onepiece'])
    ..._dimensions(scope, 'length', const [
      ('極短', 'micro'),
      ('迷你', 'mini'),
      ('膝上', 'above knee'),
      ('及膝', 'knee length'),
      ('中長', 'midi'),
      ('小腿長', 'calf length'),
      ('腳踝長', 'ankle length'),
      ('長裙', 'maxi'),
      ('拖地長度', 'floor length'),
    ]),
  ..._dimensions('outerwear', 'length', const [
    ('短版', 'cropped'),
    ('及臀', 'hip length'),
    ('及膝', 'knee length'),
    ('長版', 'long'),
  ]),
  ..._dimensions('socks', 'length', const [
    ('踝襪', 'ankle length'),
    ('中筒', 'crew length'),
    ('及膝', 'knee-high'),
    ('過膝', 'over-knee'),
    ('大腿襪', 'thigh-high'),
  ]),
];

final List<CatalogTagData> clothingOverallTags = <CatalogTagData>[
  ..._overall('outfit_main_style', '服裝・主要風格', const [
    ('休閒', 'casual style'),
    ('女性化', 'feminine style'),
    ('可愛', 'cute style'),
    ('優雅', 'elegant style'),
    ('性感', 'sexy style'),
    ('學院', 'preppy style'),
    ('街頭', 'streetwear style'),
    ('運動', 'sporty style'),
    ('哥德', 'gothic style'),
    ('龐克', 'punk style'),
    ('復古', 'vintage style'),
    ('極簡', 'minimalist style'),
    ('波希米亞', 'bohemian style'),
    ('奇幻', 'fantasy style'),
    ('未來感', 'futuristic style'),
  ]),
  ..._overall('outfit_sub_style', '服裝・子風格', const [
    ('輕鬆休閒', 'relaxed casual style'),
    ('正式休閒', 'smart casual style'),
    ('浪漫女性化', 'romantic feminine style'),
    ('甜美可愛', 'sweet cute style'),
    ('經典優雅', 'classic elegant style'),
    ('華麗性感', 'glamorous sexy style'),
    ('都市街頭', 'urban streetwear style'),
    ('機能服飾', 'techwear style'),
    ('運動休閒', 'athleisure style'),
    ('浪漫哥德', 'romantic gothic style'),
    ('維多利亞哥德', 'Victorian gothic style'),
    ('黑暗哥德', 'dark gothic style'),
    ('蒸汽龐克', 'steampunk style'),
    ('Y2K復古', 'Y2K style'),
    ('現代極簡', 'modern minimal style'),
    ('中世紀奇幻', 'medieval fantasy style'),
    ('公主奇幻', 'princess fantasy style'),
    ('女巫奇幻', 'witch fantasy style'),
    ('賽博龐克', 'cyberpunk style'),
  ]),
  ..._overall('outfit_mood', '服裝・氣質', const [
    ('可愛氣質', 'cute mood'),
    ('甜美氣質', 'sweet mood'),
    ('清純氣質', 'innocent mood'),
    ('優雅氣質', 'elegant mood'),
    ('成熟氣質', 'mature mood'),
    ('性感氣質', 'sexy mood'),
    ('冷酷氣質', 'cool mood'),
    ('強悍氣質', 'tough mood'),
    ('運動氣質', 'sporty mood'),
    ('正式氣質', 'formal mood'),
    ('奢華氣質', 'luxurious mood'),
    ('浪漫氣質', 'romantic mood'),
    ('神祕氣質', 'mysterious mood'),
    ('黑暗氣質', 'dark mood'),
    ('活潑氣質', 'playful mood'),
  ]),
  ..._overall('outfit_occasion', '服裝・場合', const [
    ('日常穿搭', 'daily outfit'),
    ('休閒外出', 'casual outing outfit'),
    ('約會穿搭', 'date outfit'),
    ('咖啡廳穿搭', 'cafe outfit'),
    ('旅行穿搭', 'travel outfit'),
    ('工作穿搭', 'work outfit'),
    ('辦公室穿搭', 'office outfit'),
    ('商務休閒', 'business casual outfit'),
    ('校園穿搭', 'school outfit'),
    ('運動穿搭', 'sports outfit'),
    ('健身房穿搭', 'gym outfit'),
    ('戶外穿搭', 'outdoor outfit'),
    ('派對穿搭', 'party outfit'),
    ('正式活動', 'formal event outfit'),
    ('婚禮賓客', 'wedding guest outfit'),
    ('海灘穿搭', 'beach outfit'),
    ('居家服', 'homewear outfit'),
    ('睡衣穿搭', 'sleepwear outfit'),
  ]),
];
