import 'catalog_data.dart';

String _expandedTagSlug(String value) => value
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
    .replaceAll(RegExp(r'^_+|_+$'), '');

List<CatalogTagData> _expandedTags({
  required String prefix,
  required String group,
  required int order,
  required bool adult,
  required List<List<String>> rows,
  String? defaultConflictGroup,
}) =>
    rows
        .map((row) => CatalogTagData(
              id: '${prefix}_${_expandedTagSlug(row[1])}',
              group: group,
              zh: row[0],
              en: row[1],
              order: order,
              adult: adult,
              conflictGroup: row.length > 2
                  ? (row[2].isEmpty ? null : row[2])
                  : defaultConflictGroup,
            ))
        .toList();

const expandedGeneralPoseGroups = <String>{
  '基礎姿勢',
  '全身姿勢',
  '軀幹姿勢',
  '頭部姿勢',
  '手臂姿勢',
  '手部姿勢',
  '腿部姿勢',
  '身體動作',
  '多人互動',
  '角色姿勢',
};

const expandedSexualPoseGroups = <String>{
  '性姿勢・一般',
  '性姿勢・後入',
  '性姿勢・女上位',
  '性姿勢・男上位',
  '性姿勢・多人',
  '束縛姿勢',
};

const expandedSexualActGroups = <String>{
  '性行為・足部',
  '性行為・摩擦',
  '性行為・手部',
  '性行為・自慰',
  '性行為・口部',
  '性行為・插入',
  '性行為・多人',
  '性行為・前後',
  'BDSM行為',
  '體液',
  '公開與窺視',
};

const expandedAdultClothingGroups = <String>{
  '情趣內衣',
  'BDSM服裝',
  '暴露服裝',
};

const expandedAdultToolGroups = <String>{
  '成人道具・插入',
  '成人道具・振動',
  'BDSM器具',
  '情趣用品',
};

const expandedSharedFinalGroups = <String>{
  ...expandedSexualPoseGroups,
  ...expandedSexualActGroups,
};

const expandedPickerTagGroups = <String>{
  ...expandedGeneralPoseGroups,
  ...expandedSexualPoseGroups,
  ...expandedSexualActGroups,
  ...expandedAdultClothingGroups,
  ...expandedAdultToolGroups,
};

const expandedTagPickerSections = <String, List<String>>{
  '基本姿態': ['姿勢', '基礎姿勢'],
  '全身與軀幹': ['全身姿勢', '軀幹姿勢'],
  '頭部姿勢': ['頭部姿勢'],
  '手臂與手勢': ['手臂姿勢', '手部姿勢'],
  '腿部與腳部': ['腿部姿勢'],
  '動態與運動': ['動作', '身體動作'],
  '多人互動': ['多人互動'],
  '物件與角色姿勢': ['物件', '角色姿勢'],
  '成人性姿勢': [
    '性姿勢',
    '性姿勢・一般',
    '性姿勢・後入',
    '性姿勢・女上位',
    '性姿勢・男上位',
    '性姿勢・多人',
  ],
  '束縛／BDSM': ['束縛姿勢', 'BDSM行為'],
  '情趣服飾': ['情趣內衣', 'BDSM服裝', '暴露服裝'],
  '成人道具': ['成人道具', '成人道具・插入', '成人道具・振動', 'BDSM器具', '情趣用品'],
  '成人行為': [
    '性行為',
    '性行為・足部',
    '性行為・摩擦',
    '性行為・手部',
    '性行為・自慰',
    '性行為・口部',
    '性行為・插入',
    '性行為・多人',
    '性行為・前後',
  ],
  '體液與公開': ['體液', '公開與窺視'],
};

final List<CatalogTagData> expandedPromptTags = <CatalogTagData>[
  ..._expandedTags(
    prefix: 'basic_pose',
    group: '基礎姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'basic_pose',
    rows: const [
      ['單膝跪地', 'on one knee'],
      ['交叉腿', 'crossed legs'],
      ['仰躺', 'on back'],
      ['趴躺', 'on stomach'],
      ['蝴蝶坐姿', 'butterfly sitting'],
      ['四字腿坐姿', 'figure four sitting'],
      ['盤腿坐姿', 'indian style'],
      ['蓮花坐姿', 'lotus position'],
      ['抱膝而坐', 'hugging own legs'],
      ['斜倚坐姿', 'reclining'],
      ['正坐', 'seiza'],
      ['坐在他人身上', 'sitting on person'],
      ['坐在頭上', 'sitting on head'],
      ['坐在腿上', 'sitting on lap'],
      ['肩扛姿勢', 'shoulder carry'],
      ['人體椅', 'human chair'],
      ['跨坐', 'straddling'],
      ['跨坐大腿', 'thigh straddling'],
      ['女坐姿', 'wariza'],
      ['橫坐', 'yokozuwari'],
    ],
  ),
  ..._expandedTags(
    prefix: 'body_movement',
    group: '身體動作',
    order: 4,
    adult: false,
    defaultConflictGroup: 'body_movement',
    rows: const [
      ['保持平衡', 'balancing'],
      ['待機動作', 'idle animation'],
      ['半空中', 'midair'],
      ['墜落中', 'falling'],
      ['漂浮', 'floating'],
      ['飛行', 'flying'],
      ['單腳跳', 'hopping'],
      ['飛撲', 'pouncing'],
      ['走路', 'walking'],
      ['行走循環', 'walk cycle'],
      ['在牆上行走', 'walking on wall'],
    ],
  ),
  ..._expandedTags(
    prefix: 'whole_body_pose',
    group: '全身姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'whole_body_pose',
    rows: const [
      ['俯伏', 'prostration'],
      ['熊式姿勢', 'bear position'],
      ['O形腿姿勢', 'bowlegged pose'],
      ['胸部支撐倒立', 'chest stand'],
      ['胸部支撐手倒立', 'chest stand handstand'],
      ['三折姿勢', 'triplefold'],
      ['魯佩爾彎曲姿勢', 'ruppelbend'],
      ['四折姿勢', 'quadfold'],
      ['畏縮姿勢', 'cowering'],
      ['十字架姿勢', 'crucifixion'],
      ['臉朝下倒地', 'faceplant'],
      ['全蠍式', 'full scorpion'],
      ['戰鬥姿勢', 'fighting stance'],
      ['拔刀術姿勢', 'battoujutsu stance'],
      ['大字型張開', 'spread eagle position'],
      ['伸展', 'stretching'],
      ['超級英雄落地', 'superhero landing'],
      ['上下顛倒', 'upside-down'],
      ['手倒立', 'handstand'],
      ['頭倒立', 'headstand'],
      ['瑜伽', 'yoga'],
      ['蠍式', 'scorpion pose'],
      ['旋轉頭碰膝式', 'revolved head-to-knee pose'],
    ],
  ),
  ..._expandedTags(
    prefix: 'torso_pose',
    group: '軀幹姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'torso_pose',
    rows: const [
      ['背部前弓', 'arched back'],
      ['背部後彎', 'bent back'],
      ['向後倚靠', 'leaning back'],
      ['向前傾', 'leaning forward'],
      ['駝背', 'slouching'],
      ['腰部後擺', 'sway back'],
      ['扭轉軀幹', 'twisted torso'],
    ],
  ),
  ..._expandedTags(
    prefix: 'head_pose',
    group: '頭部姿勢',
    order: 4,
    adult: false,
    rows: const [
      ['低頭', 'head down', 'head_vertical'],
      ['歪頭', 'head tilt', 'head_tilt'],
      ['頭向後仰', 'head back', 'head_vertical'],
      ['頭部倚靠', 'head rest', ''],
    ],
  ),
  ..._expandedTags(
    prefix: 'arm_pose',
    group: '手臂姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'arm_pose',
    rows: const [
      ['單手放在背後', 'arm behind back'],
      ['雙手放在背後', 'arms behind back'],
      ['單臂舉起', 'arm up'],
      ['單手放在頭後', 'arm behind head'],
      ['勝利姿勢', 'victory pose'],
      ['雙手放在頭後', 'arms behind head'],
      ['伸出單臂', 'outstretched arm'],
      ['伸出雙臂', 'outstretched arms'],
      ['張開雙臂', 'spread arms'],
      ['單臂垂於身側', 'arm at side'],
      ['雙臂垂於身側', 'arms at sides'],
      ['飛機式張臂', 'airplane arms'],
      ['雙臂交叉', 'crossed arms'],
      ['展示肌肉', 'flexing'],
      ['讚美太陽姿勢', 'praise the sun'],
      ['伸手觸及', 'reaching'],
      ['聳肩', 'shrugging'],
      ['T字姿勢', 't-pose'],
      ['A字姿勢', 'a-pose'],
      ['V字手臂', 'v arms'],
      ['W字手臂', 'w arms'],
    ],
  ),
  ..._expandedTags(
    prefix: 'hand_pose',
    group: '手部姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'hand_gesture',
    rows: const [
      ['撫摸自己的下巴', 'stroking own chin'],
      ['伸出手掌', 'outstretched hand'],
      ['十指交扣', 'interlocked fingers'],
      ['自己的雙手緊握', 'own hands clasped'],
      ['自己的雙手合在一起', 'own hands together'],
      ['星形手勢', 'star hands'],
      ['V字手勢', 'v'],
    ],
  ),
  ..._expandedTags(
    prefix: 'leg_pose',
    group: '腿部姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'leg_pose',
    rows: const [
      ['腳踝交叉', 'crossed ankles'],
      ['抬起單腿', 'leg up'],
      ['抬腿', 'leg lift'],
      ['伸出腿', 'outstretched leg'],
      ['固定雙腿', 'pin legs'],
      ['劈腿', 'split'],
      ['鴿式', 'pigeon pose'],
      ['站立劈腿', 'standing split'],
      ['華生交叉腿', 'watson cross'],
      ['雙腳高度不一', 'uneven footing'],
      ['膝蓋分開腳併攏', 'knees apart feet together'],
      ['膝蓋併攏腳分開', 'knees together feet apart'],
      ['抬起單膝', 'knee up'],
      ['抬起雙膝', 'knees up'],
      ['足背屈', 'dorsiflexion'],
      ['內八腳', 'pigeon-toed'],
      ['足底屈', 'plantar flexion'],
      ['腳趾蜷曲', 'toe scrunch'],
      ['踮腳', 'tiptoes'],
      ['踮腳親吻', 'tiptoe kiss'],
    ],
  ),
  ..._expandedTags(
    prefix: 'multi_person_pose',
    group: '多人互動',
    order: 4,
    adult: false,
    rows: const [
      ['臀部貼臀部', 'ass-to-ass'],
      ['背靠背', 'back-to-back'],
      ['腹部貼腹部', 'belly-to-belly'],
      ['臉頰貼胸部', 'cheek-to-breast'],
      ['臉頰貼臉頰', 'cheek-to-cheek'],
      ['眼神接觸', 'eye contact'],
      ['面對面', 'face-to-face'],
      ['額頭貼額頭', 'forehead-to-forehead'],
      ['頭靠在胸前', 'head on chest'],
      ['頭靠在一起', 'heads together'],
      ['牽手', 'holding hands'],
      ['腿部交纏', 'leg lock'],
      ['手臂互扣', 'locked arms'],
      ['趴在膝上', 'over the knee'],
      ['乳頭相貼', 'nipple-to-nipple'],
      ['鼻尖相碰', 'noses touching'],
      ['肩並肩', 'shoulder-to-shoulder'],
      ['尾巴交纏', 'tail lock'],
      ['圍成圓形', 'circle formation'],
      ['團體擁抱', 'group hug'],
      ['擁抱', 'hugging'],
      ['抱著物件', 'hugging object'],
      ['抱著尾巴', 'hugging tail'],
      ['翅膀擁抱', 'wing hug'],
      ['挽住手臂', 'arm hug'],
      ['從背後擁抱', 'hug from behind'],
      ['摟腰', 'waist hug'],
      ['嬰兒抱', 'baby carry'],
      ['抱著他人', 'carrying'],
      ['扛在肩上', 'carrying over shoulder'],
      ['夾在腋下搬運', 'carrying under arm'],
      ['兒童式抱法', 'child carry'],
      ['消防員式搬運', "fireman's carry"],
      ['背著他人', 'piggyback'],
      ['公主抱', 'princess carry'],
      ['坐在肩膀上', 'sitting on shoulder'],
      ['站在肩膀上', 'standing on shoulder'],
    ],
  ),
  ..._expandedTags(
    prefix: 'character_pose',
    group: '角色姿勢',
    order: 4,
    adult: false,
    defaultConflictGroup: 'character_pose',
    rows: const [
      ['動物姿勢', 'animal pose'],
      ['兔子姿勢', 'rabbit pose'],
      ['角狀手勢姿勢', 'horns pose'],
      ['獸爪姿勢', 'paw pose'],
      ['利爪姿勢', 'claw pose'],
      ['弓箭手姿勢', 'archer pose'],
      ['法式鄙視手勢', "bras d'honneur"],
      ['身體橋式', 'body bridge'],
      ['對立式站姿', 'contrapposto'],
      ['冒失娘姿勢', 'dojikko pose'],
      ['幽靈姿勢', 'ghost pose'],
      ['頭與髖部姿勢', 'head and hip pose'],
      ['大小姐姿勢', 'ojou-sama pose'],
      ['仙人掌姿勢', 'saboten pose'],
      ['對稱手勢', 'symmetrical hand pose'],
      ['反派姿勢', 'villain pose'],
      ['殭屍姿勢', 'zombie pose'],
      ['變身姿勢', 'henshin pose'],
      ['碇源堂姿勢', 'gendou pose'],
      ['JOJO姿勢', 'jojo pose'],
      ['迪奧姿勢', "dio brando's pose"],
      ['喬魯諾姿勢', "giorno giovanna's pose"],
      ['喬納森姿勢', "jonathan joestar's pose"],
      ['空條承太郎姿勢', "kujo jotaro's pose"],
      ['金剛姿勢', 'kongou pose'],
      ['九條可憐姿勢', 'kujou karen pose'],
      ['Z招式訓練家姿勢', 'z-move trainer pose'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_pose_general',
    group: '性姿勢・一般',
    order: 8,
    adult: true,
    defaultConflictGroup: 'sex_position',
    rows: const [
      ['六九式', '69'],
      ['側身相擁性交', 'spooning'],
      ['側臥姿勢', 'on side', 'basic_pose'],
      ['折疊姿勢', 'folded', 'leg_pose'],
      ['膝蓋貼胸', 'knees to chest', 'leg_pose'],
      ['雙腿越過頭部', 'legs over head', 'leg_pose'],
      ['交合騎乘', 'mounting'],
      ['懸空交合', 'suspended congress'],
      ['反向懸空交合', 'reverse suspended congress'],
      ['全尼爾森式', 'full nelson'],
      ['打樁機體位', 'piledriver'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_pose_rear',
    group: '性姿勢・後入',
    order: 8,
    adult: true,
    defaultConflictGroup: 'sex_position',
    rows: const [
      ['俯臥後入', 'prone bone'],
      ['俯身抬臀', 'top-down bottom-up', 'whole_body_pose'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_pose_female_top',
    group: '性姿勢・女上位',
    order: 8,
    adult: true,
    defaultConflictGroup: 'sex_position',
    rows: const [
      ['女方在上', 'girl on top'],
      ['亞馬遜體位', 'amazon position'],
      ['蹲式女上位', 'squatting cowgirl position'],
      ['反向女上位', 'reverse cowgirl position'],
      ['反向蹲式女上位', 'reverse squatting cowgirl position'],
      ['反向直立跨坐', 'reverse upright straddle'],
      ['直立跨坐', 'upright straddle'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_pose_male_top',
    group: '性姿勢・男上位',
    order: 8,
    adult: true,
    defaultConflictGroup: 'sex_position',
    rows: const [
      ['男方在上', 'boy on top'],
      ['鐵砧體位', 'anvil position'],
      ['站立傳教士體位', 'standing missionary'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_pose_multi',
    group: '性姿勢・多人',
    order: 8,
    adult: true,
    defaultConflictGroup: 'sex_position',
    rows: const [
      ['前後同時口交', 'spitroast'],
      ['反向前後同時口交', 'reverse spitroast'],
    ],
  ),
  ..._expandedTags(
    prefix: 'bondage_pose',
    group: '束縛姿勢',
    order: 8,
    adult: true,
    rows: const [
      ['手臂被綁', 'bound arms'],
      ['手肘被綁', 'bound elbows'],
      ['手指被綁', 'bound fingers'],
      ['手腕被綁', 'bound wrists'],
      ['胸部被綁', 'bound breasts'],
      ['腿部被綁', 'bound legs'],
      ['小腿被綁', 'bound calves'],
      ['雙腳被綁', 'bound feet'],
      ['膝蓋被綁', 'bound knees'],
      ['大腿被綁', 'bound thighs'],
      ['腳趾被綁', 'bound toes'],
      ['陰莖被綁', 'bound penis'],
      ['尾巴被綁', 'bound tail'],
      ['軀幹被綁', 'bound torso'],
      ['箱式綁法', 'box tie', 'bondage_tie'],
      ['反向祈禱綁法', 'reverse prayer', 'bondage_tie'],
      ['蛙式綁法', 'frogtie', 'bondage_tie'],
      ['豬綁式', 'hogtie', 'bondage_tie'],
      ['雙臂分開束縛', 'arms bound apart'],
      ['雙腿分開束縛', 'legs bound apart'],
      ['雙腕分開束縛', 'wrists bound apart'],
      ['蝦縛', 'shrimp tie', 'bondage_tie'],
      ['反吊縛', 'strappado', 'bondage_tie'],
      ['懸吊束縛', 'suspension', 'bondage_tie'],
      ['手銬連接項圈', 'cuffs-to-collar', 'bondage_tie'],
    ],
  ),
  ..._expandedTags(
    prefix: 'lingerie',
    group: '情趣內衣',
    order: 2,
    adult: true,
    rows: const [
      ['情趣內衣', 'lingerie'],
      ['娃娃裝睡衣', 'babydoll'],
      ['連身絲襪衣', 'bodystocking'],
      ['胸罩', 'bra'],
      ['馬甲式胸衣', 'bustier'],
      ['細肩帶背心', 'camisole'],
      ['襯裙式睡衣', 'chemise'],
      ['束腰馬甲', 'corset'],
      ['網襪', 'fishnets'],
      ['吊襪帶', 'garter straps'],
      ['吊襪腰帶', 'garter belt'],
      ['蕾絲', 'lace'],
      ['睡裙', 'nightgown'],
      ['內褲', 'panties'],
      ['平口女內褲', 'boyshort panties'],
      ['無肩帶式下裝', 'strapless bottom'],
      ['泰迪式內衣', 'teddy'],
      ['大腿襪', 'thighhighs'],
      ['丁字褲', 'thong'],
      ['G弦褲', 'g-string'],
      ['珍珠丁字褲', 'pearl thong'],
      ['男性內衣', 'male underwear'],
      ['陰囊胸罩', 'ball bra'],
      ['四角褲', 'boxers'],
      ['三角內褲', 'briefs'],
      ['貼身四角褲', 'boxer briefs'],
      ['比基尼三角褲', 'bikini briefs'],
      ['護襠內褲', 'jockstrap'],
      ['陰莖套', 'penis sheath'],
    ],
  ),
  ..._expandedTags(
    prefix: 'bdsm_clothing',
    group: 'BDSM服裝',
    order: 2,
    adult: true,
    rows: const [
      ['手臂束縛套', 'armbinder'],
      ['拘束服', 'bitchsuit'],
      ['緊身衣', 'bodysuit'],
      ['束縛手套', 'bondage mittens'],
      ['束縛服裝', 'bondage outfit'],
      ['貞操帶', 'chastity belt'],
      ['貞操籠', 'chastity cage'],
      ['奴役面具', 'gimp mask'],
      ['奴役緊身衣', 'gimp suit'],
      ['乳膠材質', 'latex'],
    ],
  ),
  ..._expandedTags(
    prefix: 'revealing_clothing',
    group: '暴露服裝',
    order: 2,
    adult: true,
    rows: const [
      ['臀部鏤空', 'ass cutout'],
      ['露臀泳裝', 'assless swimsuit'],
      ['露臀內褲', 'backless panties'],
      ['露臀褲子', 'backless pants'],
      ['肛門鏤空', 'anus cutout'],
      ['胸部鏤空', 'breast cutouts'],
      ['露胸服裝', 'breastless clothes'],
      ['無罩杯比基尼', 'cupless bikini'],
      ['無罩杯胸罩', 'cupless bra'],
      ['乳頭鏤空', 'nipple cutout'],
      ['襠部鏤空', 'crotchless'],
      ['開襠燈籠褲', 'crotchless bloomers'],
      ['開襠運動短褲', 'crotchless buruma'],
      ['開襠連體衣', 'crotchless leotard'],
      ['開襠內褲', 'crotchless panties'],
      ['開襠褲', 'crotchless pants'],
      ['開襠連褲襪', 'crotchless pantyhose'],
      ['開襠泳裝', 'crotchless swimsuit'],
      ['暴露服裝', 'revealing clothes'],
      ['反向服裝', 'reverse outfit'],
      ['反向比基尼盔甲', 'reverse bikini armor'],
      ['反向兔女郎裝', 'reverse bunnysuit'],
      ['肛門球穿戴', 'anal ball wear'],
      ['前貼布', 'maebari'],
      ['乳環洋裝', 'nipple ring dress'],
      ['乳貼', 'pasties'],
    ],
  ),
  ..._expandedTags(
    prefix: 'insertion_toy',
    group: '成人道具・插入',
    order: 5,
    adult: true,
    rows: const [
      ['肛珠', 'anal beads'],
      ['肛門尾巴塞', 'anal tail'],
      ['男性自慰杯', 'onahole'],
      ['臀部自慰杯', 'ass onahole'],
      ['TENGA自慰杯', 'tenga'],
      ['肛塞', 'butt plug'],
      ['寶石肛塞', 'jewel butt plug'],
      ['陰莖環', 'cock ring'],
      ['假陰莖', 'dildo'],
      ['假陰莖口塞', 'dildo gag'],
      ['面具下的假陰莖', 'dildo under mask'],
      ['假陰莖背帶', 'dildo harness'],
      ['內褲下的假陰莖', 'dildo under panties'],
      ['雙頭假陰莖', 'double dildo'],
      ['巨大假陰莖', 'huge dildo'],
      ['龍形假陰莖', 'dragon dildo'],
      ['馬形假陰莖', 'horse dildo'],
      ['尖刺假陰莖', 'spiked dildo'],
      ['穿戴式假陰莖', 'strap-on'],
      ['吸盤假陰莖', 'suction cup dildo'],
      ['騎乘假陰莖', 'dildo riding'],
      ['前列腺按摩器', 'prostate massager'],
      ['Aneros前列腺按摩器', 'aneros'],
      ['尿道探入', 'sounding'],
      ['導尿管', 'catheter'],
      ['尿道珠', 'urethral beads'],
    ],
  ),
  ..._expandedTags(
    prefix: 'vibration_toy',
    group: '成人道具・振動',
    order: 5,
    adult: true,
    rows: const [
      ['按摩器', 'vibrator'],
      ['蝴蝶型按摩器', 'butterfly vibrator'],
      ['陰蒂吸吮按摩器', 'clitoral suction vibrator'],
      ['蛋型按摩器', 'egg vibrator'],
      ['日立魔法棒', 'hitachi magic wand'],
      ['公共場所按摩器', 'public vibrator'],
      ['兔型按摩器', 'rabbit vibrator'],
      ['遙控按摩器', 'remote control vibrator'],
      ['騎乘機器', 'riding machine'],
      ['Sybian騎乘器', 'sybian'],
      ['衣物下按摩器', 'vibrator under clothes'],
      ['大腿帶上的按摩器', 'vibrator in thigh strap'],
      ['大腿襪內的按摩器', 'vibrator in thighhighs'],
      ['內褲下按摩器', 'vibrator under panties'],
      ['連褲襪下按摩器', 'vibrator under pantyhose'],
      ['肛門內按摩器', 'vibrator in anus'],
      ['乳頭上的按摩器', 'vibrator on nipple'],
      ['陰莖上的按摩器', 'vibrator on penis'],
      ['華滕伯格滾輪', 'wartenberg wheel'],
    ],
  ),
  ..._expandedTags(
    prefix: 'other_sex_toy',
    group: '情趣用品',
    order: 5,
    adult: true,
    rows: const [
      ['乳房吸乳器', 'breast pump'],
      ['陰蒂吸引器', 'clitoris pump'],
      ['陰莖幫浦', 'penis pump'],
      ['充氣娃娃', 'sex doll'],
      ['性愛機器', 'sex machine'],
      ['成人玩具', 'sex toy'],
      ['過多成人玩具', 'too many sex toys'],
    ],
  ),
  ..._expandedTags(
    prefix: 'bdsm_gear',
    group: 'BDSM器具',
    order: 5,
    adult: true,
    rows: const [
      ['肛門鉤', 'anal hook'],
      ['眼罩', 'blindfold'],
      ['鎖鏈', 'chain'],
      ['乳頭鏈', 'nipple chain'],
      ['貞操胸罩', 'chastity bra'],
      ['陰蒂夾', 'clitoris clamp'],
      ['乳頭夾', 'nipple clamps'],
      ['舌夾', 'tongue clamp'],
      ['項圈', 'collar'],
      ['拘束環', 'cuffs'],
      ['手銬', 'handcuffs'],
      ['跛行腳鐐', 'hobble'],
      ['腳鐐', 'shackles'],
      ['口塞', 'gag'],
      ['球型口塞', 'ball gag'],
      ['咬棒口塞', 'bit gag'],
      ['布條口塞', 'cleave gag'],
      ['口塞頭帶', 'gag harness'],
      ['內褲口塞', 'panty gag'],
      ['塞入式口塞', 'plug gag'],
      ['環形口塞', 'ring gag'],
      ['膠帶封口', 'tape gag'],
      ['牽繩', 'leash'],
      ['陰蒂牽繩', 'clitoris leash'],
      ['陰莖牽繩', 'leash on penis'],
      ['乳頭牽繩', 'nipple leash'],
      ['鼻鉤', 'nose hook'],
      ['穿環', 'piercing'],
      ['頸手枷', 'pillory'],
      ['足枷', 'stocks'],
      ['繩索', 'rope'],
      ['胯下繩', 'crotch rope'],
      ['撐開桿', 'spreader bar'],
      ['鞭子', 'whip'],
      ['馬鞭', 'riding crop'],
      ['多尾鞭', 'flogger'],
      ['木馬', 'wooden horse'],
      ['猶大搖籃', 'judas cradle'],
    ],
  ),
  ..._expandedTags(
    prefix: 'adult_supply',
    group: '情趣用品',
    order: 5,
    adult: true,
    rows: const [
      ['催情劑', 'aphrodisiac'],
      ['灌腸', 'enema'],
      ['乳液', 'lotion'],
      ['乳液瓶', 'lotion bottle'],
      ['潤滑液', 'lube'],
    ],
  ),
  ..._expandedTags(
    prefix: 'foot_sex',
    group: '性行為・足部',
    order: 7,
    adult: true,
    rows: const [
      ['足交', 'footjob'],
      ['雙人足交', 'double footjob'],
      ['暗示足交', 'implied footjob'],
      ['協力足交', 'cooperative footjob'],
      ['穿鞋足交', 'footjob with footwear'],
      ['鞋子足交', 'footjob with shoes'],
      ['靴子足交', 'footjob with boots'],
      ['涼鞋足交', 'footjob with sandals'],
      ['穿襪足交', 'footjob with legwear'],
      ['雙腳足交', 'two-footed footjob'],
      ['反向足交', 'reverse footjob'],
      ['背後足交', 'footjob from behind'],
      ['女性足交', 'female footjob'],
      ['桌下足交', 'footjob under table'],
      ['模擬足交', 'simulated footjob'],
      ['舔腳', 'licking foot'],
      ['足部崇拜', 'foot worship'],
      ['聞腳', 'smelling feet'],
    ],
  ),
  ..._expandedTags(
    prefix: 'friction_sex',
    group: '性行為・摩擦',
    order: 7,
    adult: true,
    rows: const [
      ['隔衣摩擦', 'frottage'],
      ['腋下性交', 'armpit sex'],
      ['陰部摩擦', 'pussyjob'],
      ['背部摩擦', 'backjob'],
      ['臀部摩擦', 'buttjob'],
      ['協力陰部摩擦', 'cooperative pussyjob'],
      ['膝窩摩擦', 'kneepit sex'],
      ['腿交', 'legjob'],
      ['乳交', 'paizuri'],
      ['自體乳交', 'autopaizuri'],
      ['協力乳交', 'cooperative paizuri'],
      ['無手乳交', 'handsfree paizuri'],
      ['平胸乳交', 'naizuri'],
      ['隔衣乳交', 'paizuri over clothes'],
      ['膝上乳交', 'paizuri on lap'],
      ['衣物下乳交', 'paizuri under clothes'],
      ['男性胸肌交', 'pecjob'],
      ['垂直乳交', 'perpendicular paizuri'],
      ['跨坐乳交', 'straddling paizuri'],
      ['側向垂直乳交', 'sideways perpendicular paizuri'],
      ['大腿性交', 'thigh sex'],
      ['龜頭摩擦', 'glansjob'],
      ['隔布龜頭摩擦', 'cloth glansjob'],
    ],
  ),
  ..._expandedTags(
    prefix: 'hand_sex',
    group: '性行為・手部',
    order: 7,
    adult: true,
    rows: const [
      ['抓住他人臀部', "grabbing another's ass"],
      ['抓住他人胸部', "grabbing another's breast"],
      ['引導抓胸', 'guided breast grab'],
      ['抓胸肌', 'pectoral grab'],
      ['引導抓胸肌', 'guided pectoral grab'],
      ['扭捏乳頭', 'nipple tweak'],
      ['抓住胯部', 'crotch grab'],
      ['引導抓胯', 'guided crotch grab'],
      ['抓自己的胸部', 'grabbing own breast'],
      ['抓住軀幹', 'torso grab'],
      ['頭髮摩擦', 'hairjob'],
      ['手交', 'handjob'],
      ['愛撫睪丸', 'caressing testicles'],
      ['雙人手交', 'double handjob'],
      ['協力手交', 'cooperative handjob'],
      ['哺乳式手交', 'nursing handjob'],
      ['擁抱手交', 'cuddling handjob'],
      ['反向哺乳式手交', 'reverse nursing handjob'],
      ['從背後手交', 'reach-around'],
      ['雙手手交', 'two-handed handjob'],
    ],
  ),
  ..._expandedTags(
    prefix: 'masturbation',
    group: '性行為・自慰',
    order: 7,
    adult: true,
    rows: const [
      ['自慰', 'masturbation'],
      ['胯部摩擦', 'crotch rub'],
      ['利用建築物自慰', 'building sex'],
      ['枕頭磨蹭', 'pillow humping'],
      ['泰迪熊磨蹭', 'teddy bear sex'],
      ['桌面磨蹭', 'table humping'],
      ['女性自慰', 'female masturbation'],
      ['扶他自慰', 'futanari masturbation'],
      ['暗示自慰', 'implied masturbation'],
      ['男性自慰', 'male masturbation'],
      ['隔衣自慰', 'masturbation through clothes'],
      ['衣物下自慰', 'masturbation under clothes'],
      ['相互自慰', 'mutual masturbation'],
      ['尾巴自慰', 'tail masturbation'],
      ['尾巴摩擦', 'tailjob'],
    ],
  ),
  ..._expandedTags(
    prefix: 'oral_sex',
    group: '性行為・口部',
    order: 7,
    adult: true,
    rows: const [
      ['口交', 'oral'],
      ['舔肛', 'anilingus'],
      ['鏽長號式', 'rusty trombone'],
      ['吸吮胸部', 'breast sucking'],
      ['舔陰', 'cunnilingus'],
      ['自體舔陰', 'autocunnilingus'],
      ['暗示舔陰', 'implied cunnilingus'],
      ['陰莖口交', 'fellatio'],
      ['自體口交', 'autofellatio'],
      ['交換精液', 'cum swap'],
      ['深喉', 'deepthroat'],
      ['暗示口交', 'implied fellatio'],
      ['強制深入口交姿勢', 'irrumatio'],
      ['協力口交', 'cooperative fellatio'],
      ['多人陰莖口交', 'multiple penis fellatio'],
      ['直立六九式', 'upright 69'],
      ['抱住吸吮', 'hug and suck'],
      ['舔睪丸', 'licking testicle'],
      ['顏面騎乘', 'facesitting'],
      ['吸吮睪丸', 'testicle sucking'],
      ['舔腋下', 'licking armpit'],
    ],
  ),
  ..._expandedTags(
    prefix: 'penetrative_sex',
    group: '性行為・插入',
    order: 7,
    adult: true,
    rows: const [
      ['性交', 'sex'],
      ['陰道性交', 'vaginal'],
      ['肛交', 'anal'],
      ['女用假陽具肛交', 'pegging'],
      ['隔衣性交', 'clothed sex'],
      ['引導插入', 'guided penetration'],
      ['暗示性交', 'implied sex'],
      ['激烈性交', 'rough sex'],
      ['水下性交', 'underwater sex'],
      ['深度插入', 'deep penetration'],
      ['子宮頸插入', 'cervical penetration'],
      ['隔物插入', 'covered penetration'],
      ['大型物體插入', 'large insertion'],
      ['多重插入', 'multiple insertions'],
      ['插入造成腹部隆起', 'stomach bulge'],
      ['精液膨脹', 'cum inflation'],
      ['膨脹', 'inflation'],
      ['物體插入', 'object insertion'],
      ['陰道物體插入', 'vaginal object insertion'],
      ['肛門物體插入', 'anal object insertion'],
      ['尿道插入', 'urethral insertion'],
      ['乳頭插入', 'nipple penetration'],
      ['食物插入', 'food insertion'],
      ['尾巴插入', 'tail insertion'],
      ['指交', 'fingering'],
      ['陰道指交', 'vaginal fingering'],
      ['肛門指交', 'anal fingering'],
      ['拳交', 'fisting'],
      ['陰道拳交', 'vaginal fisting'],
      ['肛門拳交', 'anal fisting'],
    ],
  ),
  ..._expandedTags(
    prefix: 'group_sex',
    group: '性行為・多人',
    order: 7,
    adult: true,
    rows: const [
      ['多人性交', 'group sex'],
      ['三人性交', 'threesome'],
      ['四人性交', 'foursome'],
      ['五人性交', 'fivesome'],
      ['群交', 'orgy'],
      ['輪姦式多人性交', 'gangbang'],
      ['口交夾擊', 'oral sandwich'],
      ['連環口交', 'daisy chain'],
      ['雙重插入', 'double penetration'],
      ['雙重陰道插入', 'double vaginal'],
      ['雙重肛門插入', 'double anal'],
      ['三重插入', 'triple penetration'],
      ['三重陰道插入', 'triple vaginal'],
      ['多人協作', 'teamwork'],
      ['性愛列車', 'love train'],
    ],
  ),
  ..._expandedTags(
    prefix: 'sex_timing',
    group: '性行為・前後',
    order: 7,
    adult: true,
    rows: const [
      ['性交前', 'before sex'],
      ['展示自己的身體', 'presenting own body'],
      ['任君挑選', 'take your pick'],
      ['性刺激', 'stimulation'],
      ['性交後', 'after sex'],
      ['肛交後', 'after anal'],
      ['口交後', 'after fellatio'],
      ['足交後', 'after footjob'],
      ['手交後', 'after handjob'],
      ['自慰後', 'after masturbation'],
      ['乳交後', 'after paizuri'],
      ['陰道性交後', 'after vaginal'],
      ['高潮餘韻', 'afterglow'],
      ['穿衣性交後', 'clothed after sex'],
    ],
  ),
  ..._expandedTags(
    prefix: 'bdsm_action',
    group: 'BDSM行為',
    order: 7,
    adult: true,
    rows: const [
      ['BDSM', 'bdsm'],
      ['束縛', 'bondage'],
      ['共同束縛', 'bound together'],
      ['胸部束縛', 'breast bondage'],
      ['困境束縛', 'predicament bondage'],
      ['公開束縛', 'public bondage'],
      ['自我束縛', 'self bondage'],
      ['繩縛', 'shibari'],
      ['衣物外繩縛', 'shibari over clothes'],
      ['衣物下繩縛', 'shibari under clothes'],
      ['女性支配', 'femdom'],
      ['強勢女性', 'assertive female'],
      ['女王角色', 'dominatrix'],
      ['羞辱', 'humiliation'],
      ['身體書寫', 'body writing'],
      ['受虐傾向', 'masochism'],
      ['公開使用', 'public use'],
      ['施虐傾向', 'sadism'],
      ['奴隸角色', 'slave'],
      ['被打屁股', 'spanked'],
      ['拉扯乳頭', 'nipple pull'],
      ['攻擊睪丸', 'ballbusting'],
      ['搔癢', 'tickling'],
      ['溫度玩法', 'temperature play'],
      ['冰塊玩法', 'ice play'],
      ['滴蠟玩法', 'wax play'],
    ],
  ),
  ..._expandedTags(
    prefix: 'body_fluids',
    group: '體液',
    order: 7,
    adult: true,
    rows: const [
      ['精液', 'cum'],
      ['射精', 'ejaculation'],
      ['體外射精', 'pull out'],
      ['顏射', 'facial'],
      ['精液滴落', 'semen drip'],
      ['精液痕跡', 'semen trail'],
      ['精液流出', 'leaking cum'],
      ['體內射精', 'creampie'],
      ['肛內射精', 'anal creampie'],
      ['口內精液', 'cum in mouth'],
      ['陰道內精液', 'cum in pussy'],
      ['肛門內精液', 'cum in ass'],
      ['舌上精液', 'cum on tongue'],
      ['臉上精液', 'cum on face'],
      ['胸部精液', 'cum on breasts'],
      ['身上精液', 'cum on body'],
      ['頭髮上精液', 'cum on hair'],
      ['衣服上精液', 'cum on clothes'],
      ['腹部精液', 'cum on stomach'],
      ['大腿上精液', 'cum on thighs'],
      ['腳上精液', 'cum on feet'],
      ['物體上精液', 'cum on object'],
      ['食物上精液', 'cum on food'],
      ['精液水窪', 'cum pool'],
    ],
  ),
  ..._expandedTags(
    prefix: 'public_adult',
    group: '公開與窺視',
    order: 7,
    adult: true,
    rows: const [
      ['暴露癖', 'exhibitionism'],
      ['公開猥褻', 'public indecency'],
      ['公開裸體', 'public nudity'],
      ['全裸配件穿著', 'zenra'],
      ['隱蔽束縛', 'stealth bondage'],
      ['隱蔽自慰', 'stealth masturbation'],
      ['隱蔽乳交', 'stealth paizuri'],
      ['隱蔽性交', 'stealth sex'],
      ['偷窺', 'voyeurism'],
      ['被撞見', 'caught'],
      ['探頭偷看', 'peeking'],
      ['突然走進來', 'walk-in'],
    ],
  ),
];
